# version: 0.2

# phases:
#   install:
#     commands:
#       - pip install -r requirements.txt
#   pre_build:
#     commands:
#       - export PYTHONPATH=$PYTHONPATH:/codebuild/output/src
#       - ls -R /codebuild/output  # List the directory contents for debugging
#   build:
#     commands:
#       - python src/components/data_ingestion.py
#       - python src/components/data_cleaning.py
#       - python src/components/data_transformation_SMOTE.py
#       - python src/components/model_trainer.py
#       - python src/components/model_optimizer_SMOTE.py

# artifacts:
#   files:
#     - '**/*'


version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt
  pre_build:
    commands:
      - export PROJECT_DIR=$(pwd)
      - echo "Project directory is $PROJECT_DIR"
      - export PYTHONPATH=$PYTHONPATH:$PROJECT_DIR/src
  build:
    commands:
      - echo "Listing contents of $PROJECT_DIR/src/src/components"
      - ls -R $PROJECT_DIR/src/src/components
      - echo "Running data ingestion"
      - python $PROJECT_DIR/src/src/components/data_ingestion.py
      - echo "Running data cleaning"
      - python $PROJECT_DIR/src/src/components/data_cleaner.py
      - echo "Running data transformation"
      - python $PROJECT_DIR/src/src/components/data_transformation_SMOTE.py
      - echo "Running model training"
      - python $PROJECT_DIR/src/src/components/model_trainer.py
      - echo "Running model optimization"
      - python $PROJECT_DIR/src/src/components/model_optimizer_SMOTE.py

artifacts:
  files:
    - '**/*'



