version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt
  pre_build:
    commands:
      - export PYTHONPATH=$PYTHONPATH:/codebuild/output/src100686156/src
      - ls -R /codebuild/output/src100686156/src  # List directory contents for debugging
  build:
    commands:
      - ls -R src/components  # Ensure we are in the correct directory
      - python src/components/data_ingestion.py
      - python src/components/data_cleaning.py
      - python src/components/data_transformation_SMOTE.py
      - python src/components/model_trainer.py
      - python src/components/model_optimizer_SMOTE.py

artifacts:
  files:
    - '**/*'
