branch-defaults:
  default:
    environment: Disaster-tweets-app-env
global:
  application_name: disaster-tweets-app
  default_platform: Python 3.11
  default_region: us-east-1
  profile: default
  workspace_type: Application
